### ISSUE TITLE
Normal cart price rule not applicable when module is active

### ISSUE THREAD

**Issue by luemic** [dadolun95/magento2-newsletter-coupon#1]
Hi,

I've encountered the following problem. I installed and enabled the module, but din't configured it yet. However if any existing coupon should be applied the customer get's the error "The coupon "%1" can\'t be utilized: subscription is not valid or coupon was already used.". After digging around I found that the error came from the module. I digged a bit further an found out that the subscriberInformationRepository returns an empty object. Due to the checks below in CheckNewsletterCoupon.php the error is raised.

`$subscriberInformation = $this->subscriberInformationRepository->getByCouponId($coupon->getCouponId());

            if ($subscriberInformation != null) {

                if ($subscriberInformation->getIsEnabled() !== "1") { `

Maybe there's a misconfiguration on my side or is it a bug in the module?

Kind regards

Michael

**Comment by dadolun95** [comment]
Hi @luemic 

I've installed the module on many magento2 sites in the past without running into this problem.
Maybe test doesn't highlight this error cause i've always configured the module after installing it.
I've tested minutes ago the module on a fresh magento 2.4.5 instance and received the same error.
So i've fixed the module's bug and released a new 1.0.3 version that fix it.
Let me know if is alright now.

Regards,
Davide
